# Copyright 2024 Kristoffer Winther Balling
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Molecule verify configuration for bacularis

---

- name: "Verify"
  hosts: "all"
  become: true
  gather_facts: false

  tasks:
    - name: "Check if connection still works"
      ansible.builtin.ping:
